version: "3.7"
services:
  app:
    build:
      args:
        user: katya
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: org-app
    container_name: org-app-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - org-app
  db:
    image: mysql:5.7
    container_name: org-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - org-app
  nginx:
    image: nginx:1.17-alpine
    container_name: org-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - org-app

networks:
  org-app:
    driver: bridge
